"""
TruthLens — Fake News Detection System
Training Script

To use with real Kaggle dataset:
1. Download from: https://www.kaggle.com/datasets/clmentbisaillon/fake-and-real-news-dataset
2. Place Fake.csv and True.csv in ./data/
3. Run: python train_model.py

Requirements: pip install scikit-learn pandas numpy kaggle joblib
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import PassiveAggressiveClassifier
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, classification_report
import joblib, json, re, os
from flask import Flask, request, jsonify
from flask_cors import CORS
from newspaper import Article

# ─── Option 1: Download from Kaggle ──────────────────────
# Requires: pip install kaggle
# And: ~/.kaggle/kaggle.json with your API key
def download_kaggle():
    try:
        import kaggle
        kaggle.api.authenticate()
        kaggle.api.dataset_download_files(
            'clmentbisaillon/fake-and-real-news-dataset',
            path='./data/', unzip=True
        )
        print("Dataset downloaded from Kaggle!")
        return True
    except Exception as e:
        print(f"Kaggle download failed: {e}")
        return False

# ─── Option 2: Load existing CSVs ────────────────────────
def load_kaggle_data():
    fake = pd.read_csv('./data/Fake.csv')
    real = pd.read_csv('./data/True.csv')
    fake['label'] = 0
    real['label'] = 1
    df = pd.concat([fake, real], ignore_index=True)
    return df

# ─── Option 3: Use bundled synthetic data ────────────────
def load_synthetic_data():
    return pd.read_csv('./data/news.csv')

# ─── Text preprocessing ──────────────────────────────────
def clean_text(text):
    text = re.sub(r'[^a-zA-Z\s]', '', str(text).lower())
    return re.sub(r'\s+', ' ', text).strip()

# ─── Export to JS ────────────────────────────────────────
def export_model_to_js(pipeline, X_train, y_train, X_test, y_test, y_pred, acc):
    from sklearn.metrics import precision_recall_fscore_support, confusion_matrix
    tfidf = pipeline.named_steps['tfidf']
    clf = pipeline.named_steps['clf']
    
    vocab = {k: int(v) for k, v in tfidf.vocabulary_.items()}
    idf = tfidf.idf_.tolist()
    coef = clf.coef_[0].tolist()
    intercept = float(clf.intercept_[0])
    
    # Calculate top features
    words = tfidf.get_feature_names_out()
    top_indices = np.argsort(np.abs(clf.coef_[0]))[-20:]
    top_features = [{"word": str(words[i]), "weight": float(clf.coef_[0][i])} for i in reversed(top_indices)]
    
    p, r, f, _ = precision_recall_fscore_support(y_test, y_pred, zero_division=0)
    cm = confusion_matrix(y_test, y_pred).tolist()
    
    metrics = {
        "accuracy": float(acc * 100),
        "fake_precision": float(p[0] * 100),
        "fake_recall": float(r[0] * 100),
        "fake_f1": float(f[0] * 100),
        "real_precision": float(p[1] * 100),
        "real_recall": float(r[1] * 100),
        "real_f1": float(f[1] * 100),
        "confusion_matrix": cm,
        "train_samples": int(len(y_train)),
        "test_samples": int(len(y_test))
    }
    
    js_content = f"// AUTO-GENERATED BY train_model.py\n" \
                 f"const MODEL_VOCAB = {json.dumps(vocab)};\n" \
                 f"const MODEL_IDF = {json.dumps(idf)};\n" \
                 f"const MODEL_COEF = {json.dumps(coef)};\n" \
                 f"const MODEL_INTERCEPT = {intercept};\n" \
                 f"const TOP_FEATURES = {json.dumps(top_features)};\n" \
                 f"const METRICS = {json.dumps(metrics)};\n"
                 
    with open('model_weights.js', 'w', encoding='utf-8') as f:
        f.write(js_content)
    print("Exported to model_weights.js")

# ─── Main ─────────────────────────────────────────────────
def main():
    # Try Kaggle download first, then fall back
    if os.path.exists('./data/Fake.csv') and os.path.exists('./data/True.csv'):
        print("Loading Kaggle dataset...")
        df = load_kaggle_data()
    else:
        if not download_kaggle():
            print("Using synthetic dataset...")
            df = load_synthetic_data()

    df['combined'] = (df.get('title', '') + ' ' + df.get('text', '')).fillna('')
    df['clean'] = df['combined'].apply(clean_text)
    
    X_train, X_test, y_train, y_test = train_test_split(
        df['clean'], df['label'], test_size=0.2, random_state=42, stratify=df['label']
    )

    pipeline = Pipeline([
        ('tfidf', TfidfVectorizer(max_features=10000, ngram_range=(1,2), stop_words='english')),
        ('clf', PassiveAggressiveClassifier(max_iter=50, C=0.5, random_state=42))
    ])

    print("Training model...")
    pipeline.fit(X_train, y_train)
    
    y_pred = pipeline.predict(X_test)
    acc = accuracy_score(y_test, y_pred)
    
    print(f"\nAccuracy: {acc:.4f}")
    print(classification_report(y_test, y_pred, target_names=['FAKE','REAL']))
    
    os.makedirs('./model', exist_ok=True)
    joblib.dump(pipeline, './model/model.pkl')
    print("Model saved to ./model/model.pkl")
    
    print("Exporting model weights to JavaScript...")
    export_model_to_js(pipeline, X_train, y_train, X_test, y_test, y_pred, acc)

if __name__ == '__main__':
    main()

# ─── LOAD TRAINED MODEL ────────────────────────────────

pipeline = joblib.load('./model/model.pkl')

# ─── FLASK APP ────────────────────────────────────────

app = Flask(__name__)
CORS(app)

# ─── TEXT ANALYSIS ────────────────────────────────────

@app.route('/analyze-text', methods=['POST'])
def analyze_text():

    data = request.json
    text = data.get('text', '')

    cleaned = clean_text(text)

    prediction = pipeline.predict([cleaned])[0]

    result = "REAL NEWS" if prediction == 1 else "FAKE NEWS"

    return jsonify({
        "prediction": result,
        "text": text
    })

# ─── URL ANALYSIS ─────────────────────────────────────

@app.route('/analyze-url', methods=['POST'])
def analyze_url():

    try:

        data = request.json
        url = data.get('url')

        article = Article(url)

        article.download()
        article.parse()

        title = article.title
        content = article.text

        cleaned = clean_text(content)

        prediction = pipeline.predict([cleaned])[0]

        result = "REAL NEWS" if prediction == 1 else "FAKE NEWS"

        return jsonify({
            "title": title,
            "content": content,
            "prediction": result
        })

    except Exception as e:

        return jsonify({
            "error": str(e)
        }), 500

# ─── START SERVER ─────────────────────────────────────

if __name__ == '__main__':

    # train model first
    main()

    # then run flask server
    app.run(debug=True)